### PR TITLE
fix: Allow Exceptions to Auto-populate Header

### LINKED ISSUE #57: Don’t override any existing tables of contents.
* Look for `<ul class="toc">` and if found, don't generate one.
* Also add `class="toc"` to the one we generate so that authors can style it if they want.

### PR DESCRIPTION
**Pull request by ericawright**
Fixes #57.

### CODE REVIEW

File: src/components/Editor.jsx [hunk 1]
```diff
@@ -52,7 +52,7 @@ const Editor = React.createClass({
       }
     });
 
-    if (node.querySelector('header')) {
+    if (node.querySelector('header') && !node.querySelector('header').contains(node.querySelector('.toc'))) {
```
Comment (bwinton) [inline src/components/Editor.jsx]: I think it might be more performant to write this as `!node.querySelector('header').querySelector('.toc')` (because we only need to look for the `.toc` in the `header`).

File: src/components/Editor.jsx [hunk 2]
```diff
@@ -52,7 +52,7 @@ const Editor = React.createClass({
...
       let header_list = document.createElement('ul');
```
Comment (bwinton) [inline src/components/Editor.jsx]: And while we're here, we should probably add a `class="toc"` to this element, to let the designers style it if they want…
